language: java
jdk:
  - oraclejdk8
deploy:
  provider: releases
  prerelease: true
  api_key: "$token"
  file: "./target/thunderstorm-algorithms.jar"
  skip_cleanup: true
  on:
    tags: true
after_success:
  - bash <(curl -s https://codecov.io/bash)
